import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { indexedDB } from 'fake-indexeddb';
import express from 'express';
import { once } from 'node:events';
import { createWebRelay } from '../server/web-relay.mjs';
const require=createRequire(import.meta.url),{build}=createRequire(require.resolve('vite'))('esbuild');
globalThis.indexedDB=indexedDB;globalThis.window=Object.assign(new EventTarget(),{indexedDB,isSecureContext:true});
Object.defineProperty(globalThis,'navigator',{value:{locks:{request:async(_name,_opts,work)=>work({})}},configurable:true});
const built=await build({stdin:{contents:"export {webAPI} from './src/web-api.ts'; export {webPayload} from './src/web-payload.ts'; export * from './src/local-vault.ts';",resolveDir:process.cwd(),loader:'ts'},bundle:true,format:'esm',platform:'node',write:false,logLevel:'silent'});
const client=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const fetchReal=fetch;
test('web news is credential-free, sends no brief or corpus, merges only news and persists per-user encrypted tags',async t=>{
  const root=express(),server=root.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}`;
  globalThis.location=new URL(base);const requests=[];
  const relay=createWebRelay({publicOrigin:base,allowLocalHttp:true,workspaceOptions:{newsResolver:async()=>[{address:'8.8.8.8',family:4}],newsFetcher:async url=>new Response(url.endsWith('/robots.txt')?'User-agent: *\nAllow: /':url.endsWith('.xml')?`<rss><channel><item><title>校园社交：开学季的学习搭子</title><link>https://www.chinanews.com.cn/edu/123.shtml</link><pubDate>${new Date(Date.now()-60000).toUTCString()}</pubDate><description>大学生在开学季寻找学习搭子。</description></item></channel></rss>`:'<article><p>校园社交的真实情景，开学季同学们寻找学习搭子并组织图书馆自习。</p></article>'),fetcher:async()=>{throw Error('No paid API expected');}}});root.use(relay);
  globalThis.fetch=async(url,init)=>{requests.push(JSON.parse(init.body));return fetchReal(base+url,init);};
  t.after(async()=>{globalThis.fetch=fetchReal;client.lockLocalWorkspace();await relay.locals.close();server.close();});
  await client.registerLocal('热点用户甲','news-password-test-123');
  await client.webAPI('/settings/credential','PUT',{apiKey:'sk-private-test-do-not-send-12345678'});
  const p=(await client.webAPI('/state')).projects[0],brief=structuredClone(p.brief);
  await client.webAPI(`/projects/${p.id}/corpus`,'POST',{name:'私有资料',text:'不发送给新闻采集的产品事实'});
  const settings={keywords:['校园社交'],sourceIds:['cns-education'],blockTerms:[],genericTerms:[]},path=`/projects/${p.id}/trends`;
  await client.webAPI(path+'/settings','PUT',{expectedRevision:0,settings});assert.equal(requests.length,0);
  const update=await client.webAPI(path+'/refresh','POST',{expectedRevision:1});assert.equal(update.result.articles.length,1);
  assert.deepEqual(requests[0].credentials,{});assert(!JSON.stringify(requests[0]).includes(brief.name));assert(!JSON.stringify(requests[0]).includes('私有资料'));assert(!JSON.stringify(requests[0]).includes('sk-private'));
  const result=(await client.webAPI('/state')).projects[0];assert.deepEqual(result.brief,brief);assert.equal(result.corpus[0].name,'私有资料');
  const c=result.trends.candidates[0];await client.webAPI(path+'/select','POST',{runId:result.trends.runId,candidateIds:[c.id],acknowledgedIds:[c.id],confirmed:true});assert.equal(requests.length,1);
  const after=await client.webAPI('/state');assert.equal(after.projects[0].trends.tags.length,2);
  const payload=client.webPayload(after,`/projects/${p.id}/strategies`,{},p.id);assert.equal(payload.projects[0].trends,undefined);
  client.lockLocalWorkspace();await client.registerLocal('热点用户乙','news-password-test-456');assert.equal((await client.webAPI('/state')).projects[0].trends,undefined);
  client.lockLocalWorkspace();await client.loginLocal('热点用户甲','news-password-test-123');assert.equal((await client.webAPI('/state')).projects[0].trends.tags.length,2);
});
