import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { indexedDB } from 'fake-indexeddb';
import express from 'express';
import { once } from 'node:events';
import { createWebRelay } from '../server/web-relay.mjs';
import { defaultSeedream } from '../server/seedream-config.mjs';
const require = createRequire(import.meta.url), { build } = createRequire(require.resolve('vite'))('esbuild');
globalThis.indexedDB = indexedDB;
globalThis.window = Object.assign(new EventTarget(), { indexedDB, isSecureContext: true });
const locks = new Set();
Object.defineProperty(globalThis, 'navigator', { value: { locks: { request: async (name, _options, work) => { if (locks.has(name)) return work(null); locks.add(name); try { return await work({ name }); } finally { locks.delete(name); } } } }, configurable: true });
const built = await build({ stdin: { contents: "export { webAPI } from './src/web-api.ts'; export * from './src/local-vault.ts';", resolveDir: process.cwd(), loader: 'ts' }, bundle: true, format: 'esm', platform: 'node', write: false, logLevel: 'silent' });
const client = await import('data:text/javascript;base64,' + Buffer.from(built.outputFiles[0].text).toString('base64'));
const nodeFetch = globalThis.fetch;
const ok = data => Response.json({ data: { error_code: 0, ...data } });
const apiKey = 'sk-browser-test-only-123456789012345';

test('browser flow keeps credentials encrypted locally, persists online results, and protects interrupted calls', async t => {
  const app = express(), server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
  const base = `http://127.0.0.1:${server.address().port}`; globalThis.location = new URL(base);
  let upstream = [], sent = [], loseResponse = false, providerFailure = '';
  const relay = createWebRelay({ publicOrigin: base, allowLocalHttp: true, workspaceOptions: { fetcher: async (url, init) => {
    upstream.push({ url, init });
    if (url === 'https://ark.cn-beijing.volces.com/api/v3/images/generations') return Response.json({ data: [{ b64_json: 'iVBORw0KGgo=' }], usage: { generated_images: 1 } });
    if (url === 'https://api.deepseek.com/models') return Response.json({ data: [{ id: 'deepseek-flash' }, { id: 'deepseek-v4-pro' }] });
    if (url === 'https://api.deepseek.com/user/balance') return Response.json({ is_available: true, balance_infos: [{ currency: 'CNY', total_balance: '9.99' }] });
    if (url === 'https://api.deepseek.com/chat/completions') return Response.json({ choices: [{ finish_reason: 'stop', message: { content: JSON.stringify({ title: 'DeepSeek web result', core: '真实产品', direction: '便携展示', prompt: '按产品事实展示' }) } }], usage: { prompt_tokens: 100, completion_tokens: 100 } });
    if (url.endsWith('/models')) return Response.json({ data: [{ id: 'gpt-5.4' }] });
    if (url.endsWith('/responses') && providerFailure) return Response.json({ error: { code: providerFailure, message: apiKey } }, { status: 429, headers: { 'Retry-After': '120' } });
    if (url.includes('/oauth/access_token')) return ok({ access_token: 'access-only-local', refresh_token: 'refresh-only-local', open_id: 'douyin-user-one', expires_in: 7200, refresh_expires_in: 86400, scope: 'video.create,video.data,item.comment' });
    if (url.includes('/video/upload/')) return ok({ video: { video_id: 'upload-one' } });
    if (url.includes('/video/create/')) return ok({ item_id: 'item-one' });
    if (url.includes('/video/data/')) return ok({ list: [{ item_id: 'item-one', is_reviewed: true, video_status: 5, share_url: 'https://www.douyin.com/video/123' }] });
    if (url.includes('/item/comment/list/')) return ok({ list: [{ comment_id: 'comment-one', content: '适合带去露营吗？', create_time: 1780000000, digg_count: 3 }], has_more: false, cursor: 1 });
    return Response.json({ status: 'completed', output: [{ content: [{ type: 'output_text', text: JSON.stringify({ title: '网页版真实流程测试', core: '真实产品', direction: '便携展示', prompt: '按产品事实展示' }) }] }], usage: { input_tokens: 100, output_tokens: 100 } });
  } } }); app.use(relay);
  globalThis.fetch = async (url, init) => { assert.equal(url, '/api/web/execute'); sent.push(JSON.parse(init.body)); const response = await nodeFetch(base + url, init); if (loseResponse) { loseResponse = false; throw new Error('模拟连接中断'); } return response; };
  t.after(async () => { globalThis.fetch = nodeFetch; client.lockLocalWorkspace(); const stopped = new Promise(resolve => server.close(resolve)); server.closeIdleConnections(); await relay.locals.close(); await stopped; });
  await client.registerLocal('网页版甲', 'browser-password-123');
  await client.webAPI('/guide', 'PUT', { action: 'tips', enabled: false });
  await client.webAPI('/settings/credential', 'PUT', { apiKey });
  assert.equal(sent.length, 0, 'saving a key never sends it to the server');
  await client.rememberLocalUser(); client.lockLocalWorkspace();
  assert.equal((await client.rememberedLocalUsers())[0].username, '网页版甲');
  await client.quickLoginLocal('网页版甲');
  assert.equal((await client.webAPI('/settings')).credential.suffix, apiKey.slice(-4));
  const backup = await client.webAPI('/backup'); assert(!JSON.stringify(backup).includes(apiKey)); assert(!backup.webPrivate);
  await client.webAPI('/settings/credential/check', 'POST');
  assert.equal((await client.webAPI('/settings')).verification.models[0].available, true);
  assert.equal(sent[0].state.projects.length, 0); assert(!JSON.stringify(sent[0]).includes('网页版甲'));
  assert(!sent[0].state.guide, 'local guide preferences never enter relay payloads');
  const state = await client.webAPI('/state'), p = state.projects[0];
  const other = structuredClone(p); other.id = 'other-project'; other.brief.name = '不应发送的其他项目';
  await client.changeLocalState(s => s.projects.push(other));
  await client.webAPI(`/projects/${p.id}/strategies`, 'POST', { mode: 'openai' });
  assert.equal((await client.webAPI('/state')).projects[0].strategies.at(-1).title, '网页版真实流程测试');
  assert(!JSON.stringify(sent.at(-1)).includes(other.brief.name));
  client.lockLocalWorkspace(); await client.loginLocal('网页版甲', 'browser-password-123');
  assert.equal((await client.webAPI('/state')).projects[0].strategies.at(-1).title, '网页版真实流程测试');
  loseResponse = true;
  await assert.rejects(client.webAPI(`/projects/${p.id}/strategies`, 'POST', { mode: 'openai' }), /中断/);
  assert((await client.webAPI('/settings')).pendingWebRequest);
  const count = upstream.length;
  await assert.rejects(client.webAPI(`/projects/${p.id}/strategies`, 'POST', { mode: 'openai' }), /尚未确认/);
  assert.equal(upstream.length, count, 'an uncertain request cannot be replayed automatically');
  await client.webAPI('/web/acknowledge', 'POST', { confirmed: true });
  assert.equal((await client.webAPI('/settings')).pendingWebRequest, undefined);
  // OAuth nonce and exchanged tokens survive only in the encrypted browser workspace.
  await client.webAPI('/integrations/douyin', 'PUT', { clientKey: 'app-key-local', clientSecret: 'app-secret-local', redirectUri: base + '/oauth/douyin/callback' });
  const account = state.accounts.find(a => a.platform === 'douyin');
  const prepared = await client.webAPI('/integrations/douyin/authorize', 'POST', { accountId: account.id });
  const nonce = new URL(prepared.url).searchParams.get('state');
  await client.webAPI('/integrations/douyin/complete', 'POST', { callbackUrl: base + '/oauth/douyin/callback?state=' + nonce + '&code=test-code' });
  assert.equal((await client.webAPI('/integrations')).douyin.accounts.length, 1);
  await client.changeLocalState(s => { s.projects[0].sample = false; });
  const currentProject = (await client.webAPI('/state')).projects[0];
  const ready = await client.webAPI(`/projects/${p.id}/strategies/${currentProject.strategies.at(-1).id}/confirm`, 'POST', {});
  const video = ready.state.projects[0].assets.find(a => a.kind === 'video');
  const mp4 = 'data:video/mp4;base64,' + Buffer.from('000000186674797069736f6d0000000069736f6d', 'hex').toString('base64');
  await client.webAPI(`/projects/${p.id}/assets/${video.id}`, 'PUT', { title: video.title, body: video.body, mediaData: mp4, mime: 'video/mp4', expectedRevision: video.revision });
  const scheduled = await client.webAPI(`/projects/${p.id}/publications`, 'POST', { assetId: video.id, accountId: account.id, scheduledAt: new Date(Date.now() - 1000).toISOString() });
  const publicationPath = `/projects/${p.id}/publications/${scheduled.result.id}`;
  await client.webAPI(publicationPath + '/automatic', 'POST', { confirmed: true, text: '已核对的真实产品文案' });
  await client.webAPI('/progress-version');
  let publication = (await client.webAPI('/state')).projects[0].publications.find(r => r.id === scheduled.result.id);
  assert.equal(publication.automation.status, 'submitted');
  await client.webAPI(publicationPath + '/platform-status', 'POST', {});
  publication = (await client.webAPI('/state')).projects[0].publications.find(r => r.id === scheduled.result.id);
  assert.equal(publication.status, 'published');
  await client.webAPI('/progress-version');
  assert.equal(upstream.filter(c => c.url.includes('/video/create/')).length, 1);
  await client.webAPI(publicationPath + '/comments-sync', 'PUT', { enabled: true });
  await client.webAPI('/progress-version');
  assert.equal((await client.webAPI('/state')).projects[0].comments[0].text, '适合带去露营吗？');
  const allBackup = JSON.stringify(await client.webAPI('/backup'));
  for (const secret of ['access-only-local', 'refresh-only-local', 'app-secret-local', apiKey]) assert(!allBackup.includes(secret));
  providerFailure = 'credit_balance_exhausted';
  await assert.rejects(client.webAPI(`/projects/${p.id}/strategies`, 'POST', { mode: 'openai' }), /预付余额/);
  assert.equal((await client.webAPI('/settings')).apiDiagnostic.code, providerFailure);
  assert.equal((await client.webAPI('/settings')).pendingWebRequest, undefined);
  await client.webAPI('/settings/credential/check', 'POST');
  assert.equal((await client.webAPI('/settings')).apiDiagnostic.code, providerFailure, 'model visibility cannot clear a billing failure');
  providerFailure = 'rate_limit_exceeded';
  await assert.rejects(client.webAPI(`/projects/${p.id}/strategies`, 'POST', { mode: 'openai' }), /120 秒/);
  const requestsBeforeCooldown = upstream.length;
  client.lockLocalWorkspace(); await client.loginLocal('网页版甲', 'browser-password-123');
  await assert.rejects(client.webAPI(`/projects/${p.id}/strategies`, 'POST', { mode: 'openai' }), /等待期/);
  assert.equal(upstream.length, requestsBeforeCooldown);
  assert.equal((await client.webAPI('/settings')).pendingWebRequest, undefined);
  assert(!JSON.stringify((await client.webAPI('/settings')).apiDiagnostic).includes(apiKey));
  const dsKey = 'sk-deepseek-browser-test-only-55555555';
  const beforeSaving = sent.length;
  await client.webAPI('/settings/providers/deepseek/credential', 'PUT', { apiKey: dsKey }); assert.equal(sent.length, beforeSaving);
  await client.webAPI('/settings/providers/deepseek/credential/check', 'POST');
  assert.equal((await client.webAPI('/settings')).providers.deepseek.verification.balance.items[0].total, '9.99');
  assert.deepEqual(Object.keys(sent.at(-1).credentials), ['deepseek']);
  const routes = (await client.webAPI('/settings')).routes;
  await client.webAPI('/settings/models', 'PUT', { ...routes, strategy: 'deepseek-v4-pro' });
  await client.webAPI(`/projects/${p.id}/strategies`, 'POST', { mode: 'openai' });
  assert.deepEqual(Object.keys(sent.at(-1).credentials), ['deepseek']);
  assert.equal(upstream.at(-1).init.headers.Authorization, `Bearer ${dsKey}`);
  assert.equal((await client.webAPI('/state')).projects[0].strategies.at(-1).source, 'deepseek');
  client.lockLocalWorkspace(); await client.loginLocal('网页版甲', 'browser-password-123');
  assert.equal((await client.webAPI('/settings')).providers.deepseek.configured, true);
  assert.ok(!JSON.stringify(await client.webAPI('/backup')).includes(dsKey));
  const imageKey = 'seedream-browser-only-test-key', beforeImageSave = sent.length;
  await client.webAPI('/integrations/seedream', 'PUT', { settings: defaultSeedream, apiKey: imageKey });
  await client.webAPI('/integrations/image-provider', 'PUT', { provider: 'seedream' });
  assert.equal(sent.length, beforeImageSave, 'image credentials and preferences are saved only in the browser');
  client.lockLocalWorkspace(); await client.loginLocal('网页版甲', 'browser-password-123');
  assert.equal((await client.webAPI('/integrations')).seedream.configured, true);
  assert.equal((await client.webAPI('/integrations')).imageProvider, 'seedream');
  const currentVideo = (await client.webAPI('/state')).projects[0].assets.find(a => a.id === video.id);
  await client.webAPI(`/projects/${p.id}/assets/${video.id}/keyframes`, 'POST', { role: 'first_frame', prompt: 'Seedream portrait', expectedRevision: currentVideo.revision });
  assert.deepEqual(Object.keys(sent.at(-1).credentials), ['seedream']);
  assert.equal(upstream.at(-1).init.headers.Authorization, `Bearer ${imageKey}`);
  assert.equal((await client.webAPI('/state')).projects[0].assets.find(a => a.id === video.id).aiProduction.frames[0].provider, 'seedream');
  assert(!JSON.stringify(await client.webAPI('/backup')).includes(imageKey));
  const coverAsset = (await client.webAPI('/state')).projects[0].assets.find(a => a.kind === 'image');
  await client.webAPI(`/projects/${p.id}/corpus`, 'POST', { name: '网页版外观资料', text: '咖啡产品外观：米白色独立包装、绿色标识。' });
  const coverPath = `/projects/${p.id}/assets/${coverAsset.id}`;
  await client.webAPI(coverPath + '/cover', 'POST', { prompt: '自然光', query: '产品外观', expectedRevision: coverAsset.revision, confirmed: true });
  assert.deepEqual(Object.keys(sent.at(-1).credentials), ['seedream']);
  assert.equal(JSON.parse(upstream.at(-1).init.body).size, '1728x2304');
  let cover = (await client.webAPI('/state')).projects[0].assets.find(a => a.id === coverAsset.id);
  assert.equal(cover.aiCover.phase, 'ready'); assert.equal(cover.aiCover.corpusReferences[0].name, '网页版外观资料');
  client.lockLocalWorkspace(); await client.loginLocal('网页版甲', 'browser-password-123');
  cover = (await client.webAPI('/state')).projects[0].assets.find(a => a.id === coverAsset.id);
  const callsBeforeAdopt = upstream.length;
  await client.webAPI(coverPath + '/cover-apply', 'POST', { id: cover.aiCover.id, expectedRevision: cover.revision, confirmed: true });
  assert.equal(upstream.length, callsBeforeAdopt, 'adopting a saved image never calls the model');
  assert.equal((await client.webAPI('/state')).projects[0].assets.find(a => a.id === coverAsset.id).status, 'ready');
  assert.deepEqual(Object.keys(sent.at(-1).credentials), [], 'adopting a cover needs no provider keys');
  await client.registerLocal('网页版乙', 'browser-password-456');
  assert.equal((await client.webAPI('/integrations')).seedream.configured, false);
  assert.equal((await client.webAPI('/settings')).providers.deepseek.configured, false);
  assert.equal((await client.webAPI('/settings')).apiDiagnostic, undefined);
  assert.equal((await client.webAPI('/settings')).openaiConfigured, false);
  assert.equal((await client.webAPI('/integrations')).douyin.accounts.length, 0);
  await client.forgetLocalUser('网页版甲'); await assert.rejects(client.quickLoginLocal('网页版甲'), /快捷登录/);
  await client.loginLocal('网页版甲', 'browser-password-123'); assert.equal((await client.webAPI('/integrations')).douyin.accounts.length, 1);
});
